### ISSUE TITLE
Compiler eating memory infinitely

### ISSUE THREAD

**Issue by s5bug** [amuletml/amulet#294]
I've tried to minimize this and I just can't seem to get the same behavior when I do.

The project is at https://gitdab.com/s/ootAI. I suspect that the `equipment` record in `oot/equipment.ml` is the problem.

If `equipment: u16` is replaced with `equipment: equipment` [here (permalink)](https://gitdab.com/s/ootAI/src/commit/1628d2ea5598cad0567606ef0aa135b822022c78/oot/item_equips.ml#L16), the compiler gets stuck and eats up all my memory.

**Comment by s5bug** [comment]
As of commit [4852cffa0a](https://gitdab.com/s/ootAI/src/commit/4852cffa0aa73ad40e30a7a6c97c26f285f2126d), the compiler freezes, but applying this diff makes the compiler work properly.
```diff
diff --git a/oot/item.ml b/oot/item.ml
index d077ea2..b39ee47 100644
--- a/oot/item.ml
+++ b/oot/item.ml
@@ -7,7 +7,6 @@ open import "../mem/int.ml"
 type item =
 | DekuSticks
 | NoItem
-| UnknownItem of int

 instance decode item begin
   let decode addr =
@@ -15,12 +14,10 @@ instance decode item begin
     match code with
     | 0 -> DekuSticks
     | 255 -> NoItem
-    | x -> UnknownItem x
 end

 instance show item begin
   let show = function
   | DekuSticks -> "Deku Sticks"
   | NoItem -> "No Item"
-  | UnknownItem x -> "Unknown Item " ^ (show x)
 end
 ```
 
 What is going on?

**Comment by SquidDev** [comment]
It's the pattern matcher, because of course it is.

When [Lower your guards][guards] came out (says August 2020, but this was much earlier) Abby and I discussed switching to it. Then lockdown happened and I graduated, and um ... it never materialised.

Guess now is as good a time as any!

[guards]: https://www.microsoft.com/en-us/research/publication/lower-your-guards-a-compositional-pattern-match-coverage-checker/
